title: Project Page
options:
  navigation:
    status: all
    template: project

tabs:
  page:
    label: Project page
    icon: page
    columns:
      main:
        width: 2/3
        sections:
          gallery:
            type: fields
            fields:
              gallery:
                label: Gallery
                type: files
                # uploads: false
                uploads:
                  template: media         
                layout: list
                size: small
                multiple: true
                # query: site.files
                image:
                  icon: true
                  ratio: 4/3
                  back: white
                  cover: true 
          copy:
            type: fields
            fields:
              sectionBlocks:
                label: Text
                type: blocks
                fieldsets:
                  - sectionblock
      sidebar:
        width: 1/3
        sections:
          summary:
            type: fields
            fields:
              summary:
                label: Summary
                type: structure
                columns:
                  category:
                    width: 1/2
                  text:
                    width: 1/2
                fields:
                  category:
                    type: text
                  text:
                    type: text
          cover:
            type: fields
            fields:
              background:
                label: Background image
                type: files
                uploads: false
                layout: list
                size: small
                multiple: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 1/1
                  cover: true
          filter:
            type: fields
            fields:   
              filterSetATitle:
                label: Filter by    
                type: select
                options:
                  type: query
                  query: site.filterSet.toStructure
                  text: "{{ item.category }}"
                  value: "{{ item.category }}"
              filterSetA:
                type: structure
                label: false
                fields:
                  filter:
                    type: select
                    label: Available filters   
                    options:
                      type: query
                      query: site.filterSet.toStructure
                      text: "{{ item.filter }}"
                      value: "{{ item.filter }}"
              filterSetBTitle:
                label: Filter by    
                type: select
                options:
                  type: query
                  query: site.filterSet.toStructure
                  text: "{{ item.category }}"
                  value: "{{ item.category }}"
              filterSetB:
                type: structure
                label: false
                fields:
                  filter:
                    type: select
                    label: Available filters   
                    options:
                      type: query
                      query: site.filterSet.toStructure
                      text: "{{ item.filter }}"
                      value: "{{ item.filter }}"
  # media:
  #   label: Project media
  #   icon: dashboard
  #   columns:
  #     images:
  #       width: 1/3
  #       sections:
  #         images:  
  #           type: fields
  #           fields:
  #             images:
  #               label: Images
  #               type: files
  #               uploads:
  #                 template: image     
  #               layout: list
  #               size: small
  #               multiple: true
  #               image:
  #                 icon: true
  #                 ratio: 4/3
  #                 back: white
  #                 cover: true 
  #     audio:
  #       width: 1/3
  #       sections:
  #         audiofiles:  
  #           type: fields
  #           fields:
  #             audiofiles:
  #               label: Audio
  #               type: files
  #               uploads:
  #                 template: audio     
  #               layout: list
  #               size: small
  #               multiple: true
  #               image:
  #                 icon: true
  #                 ratio: 4/3
  #                 back: white
  #                 cover: true 
  #     video:
  #       width: 1/3
  #       sections:
  #         videofiles:  
  #           type: fields
  #           fields:
  #             videofiles:
  #               label: Video
  #               type: files
  #               uploads:
  #                 template: video     
  #               layout: list
  #               size: small
  #               multiple: true
  #               image:
  #                 icon: true
  #                 ratio: 4/3
  #                 back: white
  #                 cover: true 
