title: Project Page
options:
  navigation:
    status: all
    template: project

tabs:
  page:
    label: Project Page
    icon: page
    columns:
      main:
        width: 2/3
        sections:
          content:
            type: fields
            fields:
              mainHeadline:
                type: headline
                label: Content
                numbered: false
              summary:
                label: Summary
                type: structure
                columns:
                  category:
                    width: 1/2
                  text:
                    width: 1/2
                fields:
                  category:
                    type: text
                  text:
                    type: text
          copy:
            type: fields
            fields:
              blocks:
                label: Text
                type: blocks
                fieldsets:
                  - sectionblock
      sidebar:
        width: 1/3
        sections:
          settings:
            type: fields
            fields:
              mediaHeadline:
                type: headline
                label: Media
                numbered: false
              gallery:
                type: files
                label: Gallery
                uploads:
                  template: media         
                layout: list
                size: small
                multiple: true
                image:
                  icon: true
                  ratio: 4/3
                  back: white
                  cover: true 
          filter:
            type: fields
            fields:   
              filtersHeadline:
                type: headline
                label: Filter Settings
                numbered: false
              typeName:
                label: Filter by    
                type: text
                width: 1/2
                placeholder: Media type 
                default: "Media type"        
              types: 
                type: multiselect
                label: Available filters   
                options:
                  type: query
                  query: site.mediaFilters.toStructure
                  text: "{{ item.filter }}"
                  value: "{{ item.filter }}"
              filterName:
                label: Filter by    
                type: text
                width: 1/2
                placeholder: Process stage 
                default: "Process stage" 
              filters:
                type: multiselect
                label: Available filters   
                options:
                  type: query
                  query: site.processFilters.toStructure
                  text: "{{ item.filter }}"
                  value: "{{ item.filter }}"