title: Project Page
options:
  navigation:
    status: listed
    template: project

columns:
  cover:
    sections:
      cover:
        type: fields
        fields:
          background:
            type: files
            label: Background image
            template: image
            layout: list
            size: small
            max: 1
            image:
              back: "#000"
              icon: false
              ratio: 1/1
              cover: true
  filters:
    width: 1/1
    sections:
      filter:
        type: fields
        fields:   
          filterSetATitle:
            type: text
            label: false
            before: Filter by
            width: 1/2    
          filterSetA:
            type: structure
            label: '{{ page.filterSetATitle }}'
            width: 1/2
            fields:
              filter:
                type: text
                label: Available filters
          filterSetBTitle:
            type: text
            label: false
            before: Filter by
            width: 1/2   
          filterSetB:
            type: structure
            label: '{{ page.filterSetBTitle }}'
            width: 1/2
            fields:
              filter:
                type: text
                label: Available filters
  sidebar:
    width: 1/2
    sections:
      media:
        type: fields
        fields:
          gallery:
            label: Media
            type: files
            template: image, audio, video
            layout: list
            size: small
            multiple: true
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true 
  main:
    width: 1/2
    sections: 
      copy:
        type: fields
        fields:
          blocks:
            label: Description
            type: blocks             