title: Site

tabs:
  page:
    label: Pages
    icon: grid-full
    sections:
      projects:
        type: pages
        template:
          - project
      tools:
        type: pages
        template:
          - tool
      initiative:
        type: pages
        template:
          - initiative
      timeline:
        type: pages
        template:
          - timeline
  global:
    label: Cooperative
    icon: circle
    sections:
      copy:
        type: fields
        fields:
          blocks:
            label: Text
            width: 3/4
            type: blocks
            fieldsets:
              - sectionblock
  filters:
    label: Filter collection
    icon: filter
    sections:
      filter:
        type: fields
        fields:
          filterSet:
            label: All filters
            type: structure
            sortBy: category asc
            columns:
              category:
                width: 1/2
              filter:
                width: 1/2
            fields:
              category:
                type: text
                label: Filter category
                before: Filter by
              filter:
                type: text
                label: Filter
  media:
    label: Media collection
    icon: grid
    sections:
      media:
        type: files
        template: media
        layout: table
        columns:
          filterSetA:
            label: Filter by
          filterSetB:
            label: Filter by
          tools:
            label: Related tools
          project:
            label: Related project
        image:
          icon: true
          ratio: 1/1
          back: white
          cover: true

  # media:
  #   label: Media collection
  #   icon: dashboard
  #   columns:
  #     images:
  #       width: 1/3
  #       sections:
  #         images:  
  #           type: fields
  #           fields:
  #             images:
  #               label: Images
  #               type: files
  #               uploads:
  #                 template: image     
  #               layout: list
  #               size: small
  #               multiple: true
  #               image:
  #                 icon: true
  #                 ratio: 4/3
  #                 back: white
  #                 cover: true 
  #     audio:
  #       width: 1/3
  #       sections:
  #         audiofiles:  
  #           type: fields
  #           fields:
  #             audiofiles:
  #               label: Audio
  #               type: files
  #               uploads:
  #                 template: audio     
  #               layout: list
  #               size: small
  #               multiple: true
  #               image:
  #                 icon: true
  #                 ratio: 4/3
  #                 back: white
  #                 cover: true 
  #     video:
  #       width: 1/3
  #       sections:
  #         videofiles:  
  #           type: fields
  #           fields:
  #             videofiles:
  #               label: Video
  #               type: files
  #               uploads:
  #                 template: video     
  #               layout: list
  #               size: small
  #               multiple: true
  #               image:
  #                 icon: true
  #                 ratio: 4/3
  #                 back: white
  #                 cover: true 

