title: Site

tabs:
  page:
    label: Pages
    icon: page
    sections:
      projects:
        label: All Projects
        type: pages
        layout: list
        info: "Template: {{page.template}}"
        template:
          - project
        image: false
      tools:
        label: All Tools
        type: pages
        layout: list
        info: "Template: {{page.template}}"
        template:
          - tool
        image: false
      themes:
        label: All Themes
        type: pages
        layout: list
        info: "Template: {{page.template}}"
        template:
          - theme
        image: false
      initiative:
        label: Initiative Page
        type: pages
        layout: list
        info: "Template: {{page.template}}"
        template:
          - initiative
        create: false
        image: false
      timeline:
        label: Timeline Page
        type: pages
        layout: list
        info: "Template: {{page.template}}"
        template:
          - timeline
        create: false
        image: false
  global:
    label: Cooperative
    icon: info
    sections:
      copy:
        type: fields
        fields:
          blocks:
            label: Text
            width: 3/4
            type: blocks
            fieldsets:
              - sectionblock
  filters:
    label: Filter collection
    icon: filter
    sections:
      filter:
        type: fields
        fields:
          filterSet:
            label: All filters
            type: structure
            sortBy: category asc
            columns:
              category:
                width: 1/2
              filter:
                width: 1/2
            fields:
              category:
                type: text
                label: Filter category
                before: Filter by
              filter:
                type: text
                label: Filter
  # media:
  #   label: Media collection
  #   icon: grid
  #   sections:
  #     media:
  #       type: files
  #       template: media
  #       layout: table
  #       columns:
  #         filterSetA:
  #           label: Filter by
  #         filterSetB:
  #           label: Filter by
  #         tools:
  #           label: Related tools
  #         project:
  #           label: Related project
  #       image:
  #         icon: true
  #         ratio: 1/1
  #         back: white
  #         cover: true

