title: Site

tabs:
  page:
    label: Project Page
    icon: dashboard
    sections:
      pages:
        type: pages
        template:
          - project
  about:
    lable: Cooperative
    icon: false
    sections:
      copy:
        type: fields
        fields:
          blocks:
            label: Text
            width: 3/4
            type: blocks
            fieldsets:
              - sectionblock
  filters:
    label: Filter collection
    sections:
      filter:
        type: fields
        fields:
          filterSet:
            label: All filters
            type: structure
            sortBy: category asc
            columns:
              category:
                width: 1/2
              filter:
                width: 1/2
            fields:
              category:
                type: text
                label: Filter category
                before: Filter by
              filter:
                type: text
                label: Filter
